/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import java.util.Scanner;

@SuppressWarnings("java:S106")
public class App {
    public static void main(String... args) {
        Scanner scan = new Scanner(System.in);

        System.out.println("Выберите задачу:");
        System.out.println("1 - Сравнение расстояний точек");
        System.out.println("2 - Сумма нечетных цифр трехзначного числа");
        System.out.print("Введите номер задачи: ");

        int taskNumber = scan.nextInt();

        switch (taskNumber) {
            case 1:
                PointDistance.compareDistances(scan);
                break;
            case 2:
                OddDigitSumCalculator.calculateOddDigitSum(scan);
                break;
            default:
                System.out.println("Неверный номер задачи");
        }
        scan.close();
    }
}
