/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import java.util.Scanner;

@SuppressWarnings("java:S106")
// сравнение расстояний точек до начала координат
public class PointDistance {
    // приватный конструктор для утилитного класса
    private PointDistance() {
        throw new IllegalStateException("Utility class");
    }

    public static void compareDistances(Scanner scan) {
        double x1;
        double y1;
        double x2;
        double y2;

        x1 = scan.nextDouble();
        y1 = scan.nextDouble();

        x2 = scan.nextDouble();
        y2 = scan.nextDouble();

        double distance1 = Math.sqrt(x1 * x1 + y1 * y1);
        double distance2 = Math.sqrt(x2 * x2 + y2 * y2);

        if (distance1 < distance2) {
            System.out.println("Первая точка ближе");
        } else if (distance1 > distance2) {
            System.out.println("Вторая точка ближе");
        } else {
            System.out.println("Точки на равных расстояниях");
        }
    }
}
